// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package codewhispereriface provides an interface to enable mocking the Amazon CodeWhisperer service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package codewhispereriface

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/jjviana/codex/pkg/codewhisperer/service"
)

// CodeWhispererAPI provides an interface to enable mocking the
// codewhisperer.CodeWhisperer service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//	// myFunc uses an SDK service client to make a request to
//	// Amazon CodeWhisperer.
//	func myFunc(svc codewhispereriface.CodeWhispererAPI) bool {
//	    // Make svc.CreateArtifactUploadUrl request
//	}
//
//	func main() {
//	    sess := session.New()
//	    svc := codewhisperer.New(sess)
//
//	    myFunc(svc)
//	}
//
// In your _test.go file:
//
//	// Define a mock struct to be used in your unit tests of myFunc.
//	type mockCodeWhispererClient struct {
//	    codewhispereriface.CodeWhispererAPI
//	}
//	func (m *mockCodeWhispererClient) CreateArtifactUploadUrl(input *codewhisperer.CreateArtifactUploadUrlInput) (*codewhisperer.CreateArtifactUploadUrlOutput, error) {
//	    // mock response/functionality
//	}
//
//	func TestMyFunc(t *testing.T) {
//	    // Setup Test
//	    mockSvc := &mockCodeWhispererClient{}
//
//	    myfunc(mockSvc)
//
//	    // Verify myFunc's functionality
//	}
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type CodeWhispererAPI interface {
	CreateArtifactUploadUrl(*service.CreateArtifactUploadUrlInput) (*service.CreateArtifactUploadUrlOutput, error)
	CreateArtifactUploadUrlWithContext(aws.Context, *service.CreateArtifactUploadUrlInput, ...request.Option) (*service.CreateArtifactUploadUrlOutput, error)
	CreateArtifactUploadUrlRequest(*service.CreateArtifactUploadUrlInput) (*request.Request, *service.CreateArtifactUploadUrlOutput)

	GenerateCompletions(*service.GenerateCompletionsInput) (*service.GenerateCompletionsOutput, error)
	GenerateCompletionsWithContext(aws.Context, *service.GenerateCompletionsInput, ...request.Option) (*service.GenerateCompletionsOutput, error)
	GenerateCompletionsRequest(*service.GenerateCompletionsInput) (*request.Request, *service.GenerateCompletionsOutput)

	GenerateCompletionsPages(*service.GenerateCompletionsInput, func(*service.GenerateCompletionsOutput, bool) bool) error
	GenerateCompletionsPagesWithContext(aws.Context, *service.GenerateCompletionsInput, func(*service.GenerateCompletionsOutput, bool) bool, ...request.Option) error

	GetCodeAnalysis(*service.GetCodeAnalysisInput) (*service.GetCodeAnalysisOutput, error)
	GetCodeAnalysisWithContext(aws.Context, *service.GetCodeAnalysisInput, ...request.Option) (*service.GetCodeAnalysisOutput, error)
	GetCodeAnalysisRequest(*service.GetCodeAnalysisInput) (*request.Request, *service.GetCodeAnalysisOutput)

	ListCodeAnalysisFindings(*service.ListCodeAnalysisFindingsInput) (*service.ListCodeAnalysisFindingsOutput, error)
	ListCodeAnalysisFindingsWithContext(aws.Context, *service.ListCodeAnalysisFindingsInput, ...request.Option) (*service.ListCodeAnalysisFindingsOutput, error)
	ListCodeAnalysisFindingsRequest(*service.ListCodeAnalysisFindingsInput) (*request.Request, *service.ListCodeAnalysisFindingsOutput)

	ListCodeAnalysisFindingsPages(*service.ListCodeAnalysisFindingsInput, func(*service.ListCodeAnalysisFindingsOutput, bool) bool) error
	ListCodeAnalysisFindingsPagesWithContext(aws.Context, *service.ListCodeAnalysisFindingsInput, func(*service.ListCodeAnalysisFindingsOutput, bool) bool, ...request.Option) error

	StartCodeAnalysis(*service.StartCodeAnalysisInput) (*service.StartCodeAnalysisOutput, error)
	StartCodeAnalysisWithContext(aws.Context, *service.StartCodeAnalysisInput, ...request.Option) (*service.StartCodeAnalysisOutput, error)
	StartCodeAnalysisRequest(*service.StartCodeAnalysisInput) (*request.Request, *service.StartCodeAnalysisOutput)
}

var _ CodeWhispererAPI = (*service.CodeWhisperer)(nil)
